export const LOAD_REPORTS_SUCCESS = 'LOAD_REPORTS_SUCCESS';
export const LOAD_REPORT_SUCCESS = 'LOAD_REPORT_SUCCESS';
export const CREATE_REPORT_SUCCESS = 'CREATE_REPORT_SUCCESS';
export const UPDATE_REPORT_SUCCESS = 'UPDATE_REPORT_SUCCESS';
export const DELETE_REPORT_SUCCESS = 'DELETE_REPORT_SUCCESS';

export const LOAD_KEYWORDS_SUCCESS = 'LOAD_KEYWORDS_SUCCESS';
export const CREATE_KEYWORD_SUCCESS = 'CREATE_KEYWORD_SUCCESS';

export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';